name: my first workflow number3 med fejl

on: [push]


jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: ecchco "Hello World nr2"
      - name: multiline script
        run: |
          node -v
          npm -v
